name: Release
on:
  push:
    branches:
      - master
env:
  BIGQUERY_TABLE: jarvis-dev-268314.deployment_analytics.deployment_events

permissions:
  contents: "write"
  id-token: "write"
  pull-requests: "write"

jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release-please.outputs.release_created }}
      pr_number: ${{ steps.echo-pr.outputs.pr_number }}
    steps:
      - id: release-please
        uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: node
          package-name: indykite-sdk-web
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - uses: actions/checkout@v3
        if: ${{ steps.release-please.outputs.release_created }}

      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release-please.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release-please.outputs.release_created }}

      - name: "Build the dist package"
        run: npm run-script build
        if: ${{ steps.release-please.outputs.release_created }}

      # - name: "Verify es support of dist package"
      #   run: npm run-script check-es
      #   if: ${{ steps.release-please.outputs.release_created }}

      - name: "Publish the package"
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
