name: Release
on:
  push:
    branches:
      - master
env:
  BIGQUERY_TABLE: jarvis-dev-268314.deployment_analytics.deployment_events
jobs:
  release-please:
    name: Prepare Release notes
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.release-please.outputs.release_created }}
      pr_number: ${{ steps.echo-pr.outputs.pr_number }}
    steps:
      - id: release-please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          release-type: node
          package-name: jarvis-sdk-web
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
      - uses: actions/checkout@v2
        if: ${{ steps.release-please.outputs.release_created }}
      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release-please.outputs.release_created }}
      - run: npm install
        if: ${{ steps.release-please.outputs.release_created }}
      - name: "Build the dist package"
        run: npm run-script build
        if: ${{ steps.release-please.outputs.release_created }}
      - name: "Verify es support of dist package"
        run: npm run-script check-es
        if: ${{ steps.release-please.outputs.release_created }}
      - name: "Publish the package"
        if: ${{ steps.release-please.outputs.release_created }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get Version
        if: ${{ steps.release-please.outputs.release_created }}
        run: |
          export VERSION=$(cat package.json | jq -r '.version')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        if: ${{ always() }}
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY_BQ }}
      - name: Publish Deployment Metadata
        if: ${{ always() }}
        uses: indykite/metadata-publisher@v0
        with:
          version: ${{ env.VERSION }}
          status: ${{ job.status }}
          bigquery_table: ${{ env.BIGQUERY_TABLE }}
