name: Run tests
on:
  pull_request:

jobs:
  lint:
    name: EsLint & Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"
      - name: Install Web Project
        run: npm install
      - name: Check the code
        run: |
          npm run-script lint:prettier
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install
        run: npm install
      - name: Run Tests
        uses: artiomtr/jest-coverage-report-action@v2.0-rc.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 0
          annotations: failed-tests
